# Generated by Django 3.1.5 on 2021-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_desc', models.CharField(max_length=800)),
                ('post_author', models.CharField(max_length=50)),
                ('post_image', models.ImageField(upload_to='')),
                ('post_time', models.TimeField(auto_now_add=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
