# Generated by Django 3.1.4 on 2021-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
