# Generated by Django 3.1.4 on 2021-03-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0008_auto_20210327_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_likes',
            new_name='post_like',
        ),
    ]
