# Generated by Django 3.1.5 on 2021-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0009_auto_20210327_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=0, upload_to='image/'),
        ),
    ]
