# Generated by Django 3.1.5 on 2021-03-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0010_auto_20210328_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
