# Generated by Django 3.1.5 on 2021-03-28 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website_module', '0013_auto_20210328_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
