# Generated by Django 3.1.5 on 2021-04-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0017_auto_20210414_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_author', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
