# Generated by Django 3.1.5 on 2021-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0018_auto_20210414_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='post',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
