# Generated by Django 3.1.5 on 2021-06-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0019_auto_20210414_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
