# Generated by Django 3.1.5 on 2021-06-01 15:27

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_module', '0020_auto_20210601_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_video',
            field=models.ImageField(blank=True, default=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
